# Generated by Django 6.1.1 on 2026-09-24 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('rooms', '0002_alter_roomamenity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('demand_band', models.CharField(choices=[('low', 'Low Demand'), ('normal', 'Normal Demand'), ('high', 'High Demand'), ('surge', 'Surge Demand')], default='normal', max_length=20)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('manual_override_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('override_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='organizations.organization')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
