# Generated by Django 6.1.1 on 2026-09-21 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('BALANCE_SHEET', 'Balance Sheet'), ('PROFIT_LOSS', 'Profit & Loss'), ('CASH_FLOW', 'Cash Flow Statement'), ('AUDIT_OPINION', 'Audit Opinion'), ('ANNUAL_REPORT', 'Annual Report')], max_length=32)),
                ('period_label', models.CharField(max_length=64)),
                ('publish_date', models.DateField()),
                ('pdf_url', models.URLField(blank=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ['-publish_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareholderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ownership_units', models.PositiveIntegerField(default=0)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('investment_date', models.DateField(blank=True, null=True)),
                ('dividend_entitlement', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareholder_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shareholder Profile',
                'verbose_name_plural': 'Shareholder Profiles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DividendDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('period_label', models.CharField(help_text='e.g. Q3 2026, FY 2025-26', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='corporate.shareholderprofile')),
            ],
            options={
                'verbose_name': 'Dividend Distribution',
                'verbose_name_plural': 'Dividend Distributions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
