# Generated by Django 6.1.1 on 2026-09-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomamenity',
            options={'ordering': ['name'], 'verbose_name': 'Room Amenity', 'verbose_name_plural': 'Room Amenities'},
        ),
    ]
